export const journey = [
  {
    period: "First projects",
    category: "Learn",
    title: "Started with small websites",
    story: "I learned the basics by changing layouts, rebuilding simple pages, and checking the result in the browser.",
    lesson: "Small finished pages taught me more than collecting unfinished experiments.",
    relatedHref: null,
  },
  {
    period: "Hackathon",
    category: "Compete",
    title: "Built Mangystau Trials",
    story: "I worked on a tourism prototype with a route flow, map, budget input, and trip preferences. It did not reach the final selection.",
    lesson: "The idea needed a smaller first version and a clearer main feature.",
    relatedHref: "/work/mangystau-trials",
  },
  {
    period: "Commercial work",
    category: "Build",
    title: "Delivered 99 AKTAU",
    story: "I built the public site, booking requests, admin login, status controls, Supabase connection, and deployment setup.",
    lesson: "The client still needs clear controls and documentation after the website is published.",
    relatedHref: "/work/99-aktau",
  },
  {
    period: "Hospitality work",
    category: "Build",
    title: "Built Tuesday Lounge Bar",
    story: "I organized the venue information and built a responsive site with direct access to the menu, location, contacts, and reservation action.",
    lesson: "Content order and mobile navigation strongly affect a business website.",
    relatedHref: "/work/tuesday-lounge-bar",
  },
  {
    period: "Outside school",
    category: "Train",
    title: "Continued judo training",
    story: "Training gives me a separate place to practise, notice mistakes, correct a technique, and repeat it.",
    lesson: "A weak part becomes easier to fix when I test it again instead of guessing.",
    relatedHref: null,
  },
  {
    period: "Now",
    category: "Learn",
    title: "Improving English and web development",
    story: "I am working on clearer writing, stronger frontend fundamentals, better performance, and more reliable project handover.",
    lesson: "My current goal is to make each new project more complete than the previous one.",
    relatedHref: null,
  },
] as const;
